[package]
name = "reqchan"
version = "0.5.3"
authors = ["Philip Woods <elzairthesorcerer@gmail.com>"]
description = "A simple Request->Response channel"
license = "MIT/Apache-2.0"
homepage = "https://github.com/Elzair/reqchan-rs"

[dependencies]
